### ISSUE TITLE
[Layout]: 

### ISSUE THREAD

**Issue by kroon-lab** [COMCIFS/instrument-geometry-info#2]
### Beamline name

I04

### Configuration

Eiger 16M

### Is updated?

- [ ] Is an update

### Phi axis orientation

0 degrees

### Phi axis rotation

anticlockwise

### Goniometer axes

omega, cantilockwise, chi, anticlockwise, phi, anticlockwise

### Image orientation

top left

### Fast direction

horizontal

### Detector axes

none

**Comment by jamesrhester** [comment]
This was a test run, closing.
