### ISSUE TITLE
STOE Stadivari with Chi axis

### ISSUE THREAD

**Issue by kroon-lab** [COMCIFS/instrument-geometry-info#20]
### Name of manufacturer

Stoe

### Model

Stadivari

### Location

Benemerita Uiversidad Autonoma de Puebla

### Principal axis orientation

270

### Goniometer axes

Phi, a, Chi, c, Omega, a

### chi

180

### Image orientation

top left

### Fast direction

horizontal

### Pixel size

0.172

### Two theta axis

a

### Data DOI

10.5281/zenodo.7155191

**Comment by jamesrhester** [comment]
Note chi axis sense of rotation in the original issue is incorrect.
