### ISSUE TITLE
differences between pointers to _axis.id and construction of some loops compared to publication

### ISSUE THREAD

**Issue by julianhoersch** [COMCIFS/instrument-geometry-info#46]
This is an excerpt of #42 
There are some differences between the current output of the imgCIF_creator and the published imgCIFs:

loop_
_array_structure_list_axis.axis_id
_array_structure_list_axis.axis_set_id
_array_structure_list_axis.displacement
_array_structure_list_axis.displacement_increment
array_x 1 0.0375 0.075
array_y 2 0.0375 0.075

==> _array_structure_list_axis.axis.id is a pointer to _axis.id above. So I think that array_x should be detx, and likewise for array_y

loop_
_diffrn_detector_axis.axis_id
_diffrn_detector_axis.detector_id
det_z det1

==> again _diffrn_detector_axis.axis.id is a pointer to axis.id, and thus should be trans
loop
_diffrn_scan_axis.scan_id
_diffrn_scan_axis.axis_id
_diffrn_scan_axis.displacement_start
_diffrn_scan_axis.displacement_increment
_diffrn_scan_axis.displacement_range
_diffrn_scan_axis.angle_start
_diffrn_scan_axis.angle_increment
_diffrn_scan_axis.angle_range
SCAN1 chi . . . 0.0 0 0
SCAN1 omega . . . 0.0 0.1 360.0
SCAN1 phi . . . 0.0 0 0
SCAN1 detx . . . 0.0 0 0
SCAN1 dety . . . 0.0 0 0
SCAN1 trans 287.2224260231453 0 0 . . .

==> only omega is scanned. Leave the other _axis.id out?? I don't mind if they stay in, but normally we use only one scan-axis

**Comment by julianhoersch** [comment]
- **array_structure_list_axis.axis.id is a pointer to _axis.id above** I'll change that I was not sure if this was correct.

- **_diffrn_detector_axis.axis.id is a pointer to axis.id** I can change that as well. Actually this confused me also a bit - if you look at #30 there the `axis_id`s are
```
    loop_
      _diffrn_detector_axis.axis_id
      _diffrn_detector_axis.detector_id
         detx                     1
         dety                     1
```
and refer to detx and dety, not trans.  Should it always be the translation axis? I guess there could also be more detector axes? I was trying to infer the detector axes from the `/entry/instrument` path when the the `NX_class` attribute is  `NXpositioner` I'm not sure if that makes sense:
 ```
                # find detector axes
                # TODO can I extract it from the hdf5 with the number of nxpositioners?
                detector_axes = []
                instrument_group = h5_master[f'{scan}/instrument/']
                for sub_grp in instrument_group.keys():
                    try:
                        nx_class = instrument_group[sub_grp].attrs["NX_class"].decode('utf-8')
                        if "NXpositioner" in nx_class:
                            detector_axes.append(list(instrument_group[sub_grp].keys())[0])
                    except KeyError:
                        pass
                setup_info['detector_axes'] = detector_axes
```
- **only omega is scanned. Leave the other _axis.id out??** I can leave the other axes out if that's better. That would also mean that for other datasets, e.g. the data from #20, all axes except omega would be removed?

```
loop_
  _diffrn_scan_axis.scan_id
  _diffrn_scan_axis.axis_id
  _diffrn_scan_axis.displacement_start
  _diffrn_scan_axis.displacement_increment
  _diffrn_scan_axis.displacement_range
  _diffrn_scan_axis.angle_start
  _diffrn_scan_axis.angle_increment
  _diffrn_scan_axis.angle_range
         SCAN01    chi       .         .         .         -60.991   0         0        
         SCAN01    phi       .         .         .         -140.0    0         0        
         SCAN01    detector_2theta     .         .         .         12.4      0
          0         
         SCAN01    omega     .         .         .         -40.679   2.0       66.0     
         SCAN01    distance  40.0      0         0         .         .         .        
         SCAN02    chi       .         .         .         -60.991   0         0        
         SCAN02    phi       .         .         .         30.0      0         0        
         SCAN02    detector_2theta     .         .         .         12.4      0
          0         
         SCAN02    omega     .         .         .         -32.679   2.0       58.0     
         SCAN02    distance  40.0      0         0         .         .         .         
```
- **The construction with _diffrn_scan_axis is different** this basically results from way the `cbf_scan_extractor.jl` did it and the fact that multiple scans can be present which makes a loop necessary (see code above) 

- **diifrn_scan_frame is different** if you refer to the `integration_time` I've moved that from `_diffrn_scan.integration_time` to `_diffrn_scan_frame.integration_time` since it was done like that in the `cbf_scan_extractor.jl`

- the entries in `_diffrn_data_frame` also reflect those in the `cbf_scan_extractor.jl`

```loop_
_diffrn_data_frame.id
_diffrn_data_frame.detector_element_id
_diffrn_data_frame.array_id
_diffrn_data_frame.binary_id
```

**Comment by jamesrhester** [comment]
The reason we include all axes in `_diffrn_scan_axis`, even the ones that are not scanned, is because `cbflib` requires all axes to be included in the list, otherwise it fails. This is presumably because `cbflib` is supposed to read single-frame cbf files, and needs all axis positions present in all frames. But we can leave unscanned axes out as @kroon-lab suggests and the imgCIF file will still be correct.

**Comment by kroon-lab** [comment]
_diffrn_detector_axis.axis.id is a pointer to axis.id I can change that as well. Actually this confused me also a bit - if you look at
    https://github.com/COMCIFS/instrument-geometry-info/issues/30 there the axis_ids are
    loop_
      _diffrn_detector_axis.axis_id
      _diffrn_detector_axis.detector_id
         detx                     1
         dety                     1

@jamesrhester why would we use ### _diffrn_detector_axis anyway? The axes are already defined in ### _axis.

**Comment by jamesrhester** [comment]
`diffrn_detector_axis` simply associates detector axes with particular detectors. It is not strictly necessary when there is only one detector. However, cbflib often insists on some of these categories being present in order for cbflib geometric calculations to function properly. If we wish to simplify use of our imgCIF for those who are using cbflib, it is probably a good idea to leave these categories in.

**Comment by julianhoersch** [comment]
So I understand that `_diffrn_detector_axis.axis_id` should point to `trans`?

```
loop_
_diffrn_detector_axis.axis_id
_diffrn_detector_axis.detector_id
        trans                    1
```
not like in #30 to `detx`, `dety`
```
    loop_
      _diffrn_detector_axis.axis_id
      _diffrn_detector_axis.detector_id
         detx                     1
         dety                     1
```

**Comment by kroon-lab** [comment]
Yes, `_diffrn_detector_axis.axis_id ` should point to `trans`

@jamesrhester , was do you use `detx `and `dety ` in #30 in `_diffrn_detector_axis.axis_id` ? and why not also for `trans`
