### ISSUE TITLE
offset values in axis description

### ISSUE THREAD

**Issue by julianhoersch** [COMCIFS/instrument-geometry-info#53]
Currently the offset for the trans/distance axis in the axis description is taken from the first scan and I was wondering if this is ok if there are multiple scans with different trans/distance settings. Should the offset be 0 in the axis description?

**Comment by jamesrhester** [comment]
It would definitely be better for the offset to be zero in the axis description, and then the scan information gives the translation. I have seen experiments where different scans use different distances.

**Comment by kroon-lab** [comment]
OK with me.
